# Student Practice Problems

In [2]:

import numpy as np

##Problem 1

In [7]:
A = np.array([[3, 4],
              [2, 5]])
# Try to compute the inverse of matrix A
try:
  A_inv = np.linalg.inv(A)
  # If successful, print the inverse
  print("The inverse of matrix A is:\n", A_inv)
# Catch the LinAlgError if the matrix is singular (no inverse exists)
except np.linalg.LinAlgError:
  print("No inverse exist for this matrix.")

The inverse of matrix A is:
 [[ 0.71428571 -0.57142857]
 [-0.28571429  0.42857143]]


##Problem 2

In [ ]:
A = np.array([[2, 3], [4, -1]])  # Define matrix A
B = np.array([7, 5])  # Define matrix B

try:
  X = np.linalg.solve(A, B)  # Solve the system of linear equations AX = B
  # Print the solution
  print("The solution is:")
  print("x =", X[0])
  print("y =", X[1])
except np.linalg.LinAlgError:  #
  print("System cannot be solved.")

##Problem 3

In [4]:
A = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])

try:

# Calculate the inverse of matrix A
  A_inv = np.linalg.inv(A)
  print("The inverse of matrix_A3 is:\n", A_inv)
except np.linalg.LinAlgError:
  print("No inverse exist for this matrix.")

The inverse of matrix_A3 is:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


##Problem 4

In [5]:
# Define the coefficient matrix A and the constant vector B
A = np.array([[1, 1, 1],
              [2, 5, 1],
              [2, 3, 8]])
B = np.array([6, -4, 9])

# Calculate the inverse of matrix A
try:
  A_inv = np.linalg.inv(A)

  # Solve for the variables x, y, and z using matrix multiplication
  X = np.dot(A_inv, B)

  # Print the solution
  print("Solution:")
  print("x =", X[0])
  print("y =", X[1])
  print("z =", X[2])

except np.linalg.LinAlgError:
  print("No unique solution exists (singular matrix).")

Solution:
x = 10.842105263157896
y = -5.210526315789474
z = 0.3684210526315789


##Problem 5

In [6]:
# Define the matrix A and vector b
A = np.array([[4, -1, 0], [3, 5, 2], [-2, 4, 1]])
b = np.array([[5], [6], [2]])

# Solve for x using NumPy's linear algebra solver
try:
  x = np.linalg.solve(A, b)

  # Print the solution
  print("Solution:")
  print("x =", x[0])
  print("y =", x[1])
  print("z =", x[2])

except np.linalg.LinAlgError:
  print("System cannot be solved.")

Solution:
x = 2.5999999999999996
y = 5.399999999999998
z = -14.399999999999993


##Bonus Challenge

In [ ]:
def matrix_inverse(matrix):
  """
  Checks if a given matrix is invertible and returns its inverse if it exists.

  Args:
    matrix: A NumPy array representing the matrix.

  Returns:
    The inverse of the matrix if it's invertible, otherwise None.
  """
  try:
    determinant = np.linalg.det(matrix)
    if np.isclose(determinant, 0):  # Check for near-zero determinant
      print("The matrix is not invertible (determinant is zero).")
      return None
    else:
      inverse_matrix = np.linalg.inv(matrix)
      return inverse_matrix
  except np.linalg.LinAlgError:
    print("The matrix is not invertible.")
    return None